sudo: false
language: python
cache: pip
  directories:
    - /home/travis/virtualenv/python-3.6-debug/
    - /home/travis/python-3.6-debug/

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.6"
    env: USE_PYTHON_DEBUG_BUILD=1

install:
  - if [[ $USE_PYTHON_DEBUG_BUILD == 1 ]]; then scripts/build-debug-python.sh; fi
  - pip install -U pip setuptools wheel
  - pip install -r external/mypy/test-requirements.txt

script:
  - export PYTHONPATH=`pwd`/external/mypy
  - export PYTHONVERSION=`python --version | awk '{ print $2 }'`

  - if [[ $USE_PYTHON_DEBUG_BUILD == 1 ]]; then export PYTHONDIR="/home/travis/python-3.6-debug"; else export PYTHONDIR="/opt/python/$PYTHONVERSION"; fi
  - export PYTHONCONFIG="$PYTHONDIR/bin/python-config"
  - export LD_LIBRARY_PATH="$PYTHONDIR/lib"
  - if [[ $USE_PYTHON_DEBUG_BUILD != 1 ]]; then pytest -n4 mypyc; fi
  - if [[ $USE_PYTHON_DEBUG_BUILD == 1 ]]; then pytest -n4 mypyc/test/test_run.py mypyc/test/test_external.py -k 'not test_self_type_check'; fi
